### PR TITLE
Fix #14 double escaping

### LINKED ISSUE #14: Double escaping issue
Currently, generated links have escaped ampersands, ie for e-mail `&amp;` is used:

https://github.com/SaraVieira/react-social-sharing/blob/master/src/consts.js#L38-L41

But [React DOM escapes any value](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks) and this leads to double escaping and as a result E-mail sharing buttons (and probably others as well) do not work correctly.

From what I see fix for this would be to *unescape*  all`&amp;` in
https://github.com/SaraVieira/react-social-sharing/blob/master/src/consts.js

### PR DESCRIPTION
**Pull request by bmihelac**
first commit is failing test that demonstrate issue
last 2 commits are prettier formatting ☺️

### CODE REVIEW

**Comment by SaraVieira** [comment]
closes #14

**Comment by SaraVieira** [comment]
This looks great! I will merge now and let you know when it's published :)


Thank you 🎉

**Comment by SaraVieira** [comment]
Release in version https://github.com/SaraVieira/react-social-sharing/releases/tag/v1.3.3

Thank you again!

**Comment by bmihelac** [comment]
Thanks for merging and releasing new version 👍

**Pull request merged**
